import { Coins } from "lucide-react";

export const CASH_IN_PLANS = [
    {
        id: "starter_pack",
        name: "Starter Pack",
        icon: Coins,
        price: 5,
        currency: "USD",
        lrealAmount: 500,
        description: "Get started with 500 LREAL",
        color: "blue",
        gradient: "from-blue-500 to-cyan-500",
    },
    {
        id: "pro_pack",
        name: "Pro Pack",
        icon: Coins,
        price: 10,
        currency: "USD",
        lrealAmount: 1000,
        description: "1,000 LREAL for serious users",
        popular: true,
        color: "pink",
        gradient: "from-pink-500 to-purple-500",
    },
    {
        id: "advanced_pack",
        name: "Advanced Pack",
        icon: Coins,
        price: 20,
        currency: "USD",
        lrealAmount: 2000,
        description: "2,000 LREAL for power users",
        color: "green",
        gradient: "from-green-500 to-emerald-500",
    },
    {
        id: "ultimate_pack",
        name: "Ultimate Pack",
        icon: Coins,
        price: 50,
        currency: "USD",
        lrealAmount: 5000,
        description: "Best value: 5,000 LREAL",
        color: "orange",
        gradient: "from-yellow-500 to-orange-500",
    },
    {
        id: "mega_pack",
        name: "Mega Pack",
        icon: Coins,
        price: 100,
        currency: "USD",
        lrealAmount: 10000,
        description: "10,000 LREAL for streamers",
        color: "red",
        gradient: "from-red-500 to-rose-500",
    },
    {
        id: "ultra_pack",
        name: "Ultra Pack",
        icon: Coins,
        price: 500,
        currency: "USD",
        lrealAmount: 50000,
        description: "50,000 LREAL for verified creators",
        color: "indigo",
        gradient: "from-indigo-500 to-violet-500",
    },
];
